
# SEO settings
title: Inner Demons, Meet Jesus
description: "Want to surrender your life to God? First, you'll need to introduce your demons to the Lord..."
keywords: ""
url: http://change.me
baseurl: null

google_analytics:
repo:
disqus_shortname: "innerdemonsmeetjesus"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
# highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

# source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Inner Demons, Meet Jesus
  job      :
  bio      : ""
  thumb    :
  email    : thatgalkelly@gmail.com
  url      :
  github   :
  twitter  :
  facebook :
  linkedin :

# social settings
og_locale: "en_US"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
